"use strict"

import "./domready.mjs"
import "./events.mjs"
import "./nodes.mjs"
import "./eventTargets.mjs"
import "./eventDispatchers.mjs"
import "./event--emitting.mjs"
import "./event--broadcasting.mjs"
import "./readyStateFuls.mjs"
import "./animationFrames.mjs"
import "./serializers.mjs"
import "./models.mjs"
import "./templates--legacy.mjs"
import "./views.mjs"
import "./routers.mjs"
import "./cookies.mjs"
import "./cssrules.mjs"
import "./stylesheets.mjs"
import "./services.mjs"
import "./traits.mjs"

mocha.run()
