"use strict"

export const ERR_EVENT_NOT_IMPLEMENTED = "ERR_EVENT_NOT_IMPLEMENTED"
export const ERR_EVENT_TARGET_IS_NOT_VALID = "ERR_EVENT_TARGET_IS_NOT_VALID"
export const ERR_CANNOT_BE_REUSED = "ERR_CANNOT_BE_REUSED"
export const ERR_CSSTEXT = "ERR_CSSTEXT"
export const ERR_FN_EXPECTED = "function expected"
export const ERR_GENERATOR_EXPECTED = "ERR_GENERATOR_EXPECTED"
export const ERR_INVALID_TARGET = "ERR_INVALID_TARGET"
export const ERR_NODE_NOT_CHILD = "ERR_NODE_NOT_CHILD"
export const ERR_NODE_NOT_IMPLEMENTED = "ERR_NODE_NOT_IMPLEMENTED"
export const ERR_READYSTATEFUL_NOT_IMPLEMENTED = "ERR_READYSTATEFUL_NOT_IMPLEMENTED"
export const ERR_SAME_OBJ = "ERR_SAME_OBJ"
export const ERR_ILLEGAL_CONSTRUCTOR = "ERR_ILLEGAL_CONSTRUCTOR"
export const ERR_INVALID_DATA = "ERR_INVALID_DATA"
export const ERR_TYPE_UNKNOWN = "ERR_TYPE_UNKNOWN"
export const ERR_NOT_ITERABLE = "ERR_NOT_ITERABLE"
export const ERR_NOT_A_NODE = "ERR_NOT_A_NODE"
export const ERR_RHANDLER = "not a valid route handler"
export const ERR_ROUTE_BUSY = "route has already been used"
export const ERR_NOTROUTE = "not a valid route object"
export const ERR_SS_NOT_WRITABLE = "ERR_SS_NOT_WRITABLE"
export const ERR_STRING_EXPECTED = "ERR_STRING_EXPECTED"
export const WARN_LATE_NEXT = "WARN_LATE_NEXT"

// graph
export const EALRDYCONN = "edge is already connected to a graph"
export const EINVALIDCONS = "invalid constructor"
export const ENOTEDGE = "object does not implement Edge"
export const ENOTGRAPH = "object does not implement Graph"
export const ENOTINSET = "object does not belong to the set"
export const ENOTVERTEX = "object does not implement Vertex"
export const EPRLLLNOTALLOW = "graph doesn't allow parallel edges"
export const ETOOMANYVERT = "edges cannot hold more vertices"
export const EUNCOMPEDGE = "edge type is not allowed by this graph"
export const EUNKNWNREL = "relation is unknown"
