"use strict"

export { bound, final, frozen } from "decorators"
export cancelAnimationFrames from "utils/cancelAnimationFrames"
export Cookie, { Sync as CookieSync } from "cookies/Cookie"
export CSSConditionalRule from "css/CSSConditionalRule"
export CSSHook from "css/CSSHook"
export CSSMediaRule from "css/CSSMediaRule"
export CSSRule, { TextUpdate as CSSRuleTextUpdate, SelectorUpdate as CSSRuleSelectorUpdate, Reset as CSSRuleReset } from "css/CSSRule"
export domready from "utils/domready"
export dummy from "utils/dummy"
export Event from "events/Event"
export EventDispatcher from "events/EventDispatcher"
export EventTarget from "events/EventTarget"
export isNative from "utils/isNative"
export isSameDomain from "utils/isSameDomain"
export Model from "models/Model"
export Node from "nodes/Node"
export ReadyStateFul, { ReadyStateChange } from "utils/ReadyStateFul"
export requestAnimationFrames from "utils/requestAnimationFrames"
export Route from "routing/Route"
export RouteDispatcher from "routing/RouteDispatcher"
export Router from "routing/Router"
export Serializer from "serializers/Serializer"
export singleton from "utils/singleton"
export Stylesheet from "css/Stylesheet"
export store from "store"
export trait from "utils/trait"
export toType from "utils/toType"
export View, { expression } from "views/View"
export ZParser from "views/ZParser"

// graph
export BreadthFirstTree from "graph/BreadthFirstTree"
export DepthFirstTree from "graph/DepthFirstTree"
export Edge from "graph/Edge"
export Graph from "graph/Graph"
export HyperGraph from "graph/HyperGraph"
export Traversal from "graph/Traversal"
export Vertex from "graph/Vertex"

export default `${process.env.APPNAME}@${process.env.APPVERSION}`
